### ISSUE TITLE
teach_stu_perturbedGX.csv

### ISSUE THREAD

**Issue by wioxio** [XieResearchGroup/MultiDCP#1]
Dear team,

I want to reproduce the result but I cannot find 'teach_stu_perturbedGX.csv' and 'teach_stu_perturbedGX_hidden.csv' from 10.5281/zenodo.5172809. Has the name of the file changed or is it removed?

Thanks.

**Comment by AdorableYoyo** [comment]
Hi,

Thanks for your interest in reproducing the result. 

We have modified the code so you will not have a problem reproducing without passing those two parameters. Those two parameters allow the user to pass the file path to save the corresponding intermediate result for debugging usage, you could pass your own path if needed( from main Python file argparse. But please turn save_data=True first if you want to check the intermediate result. )

eg. --predicted_result_for_testset "../MultiDCP/data/teacher_student/teach_stu_perturbedGX.csv"  : this is to save the prediction result when save_data=True (However, script/train_multidcp_ae_infer.sh will produce the prediction result as well.)
--hidden_repr_result_for_testset "../MultiDCP/data/teacher_student/teach_stu_perturbedGX_hidden.csv" this is to save the hidden representation when save_data=True , mostly for debugging use or if you need to save embeddings for other task. 

Hope it helps. :)

**Comment by wioxio** [comment]
Thanks you so much for the information!
